### ISSUE TITLE
AttributeError: 'BSC' object has no attribute 'beta'

### ISSUE THREAD

**Issue by joshinh** [UKPLab/arxiv2018-bayesian-ensembles#3]
I get the following error when I run src/run_ner_experiments.py : AttributeError: 'BSC' object has no attribute 'beta' on line 422 of src/bsc/bsc.py which seems correct since there is no such attribute. Could you please let me know what change in code is required to run the code?

**Comment by edwinrobots** [comment]
Apologies, that bit of code should not be running any more. Also, thanks for reporting it.

I don’t currently have access to push the fix to the same repo, so please check out the fork here, where I have just fixed it. I will try to get the changes merged back into the main repo. 

https://github.com/edwinrobots/arxiv2018-bayesian-ensembles <https://github.com/edwinrobots/arxiv2018-bayesian-ensembles>

**Comment by joshinh** [comment]
Thanks, this fixed things.
